/**
 * App icons — import from `@/icons` only. See primitives and individual modules under src/icons.
 */

// Use explicit `.ts` so resolution does not pick Node's built-in `constants` under `moduleResolution: "bundler"`.
export { ICON_PX } from "./constants.ts";

export * from './AddContact';
export * from './AlertTriangle';
export * from './Approval';
export * from './Archive';
export * from './ArrowDown';
export * from './ArrowNested';
export * from './ArrowRight';
export * from './ArrowSwap';
export * from './ArrowTopRight';
export * from './Attach';
export * from './Bank';
export * from './BarChart';
export * from './Barcode';
export * from './Bell';
export * from './Briefcase';
export * from './Building';
export * from './Calculator';
export * from './Calendar';
export * from './CalendarArrowRight';
export * from './CalendarEvent';
export * from './Camera';
export * from './ChartLine';
export * from './ChainLink';
export * from './Check';
export * from './CheckCircle';
export * from './CheckFilled';
export * from './ChevronDown';
export * from './ChevronLeft';
export * from './ChevronRight';
export * from './ChevronUp';
export * from './ChevronUpFilled';
export * from './ChevronsDown';
export * from './ChevronsLeft';
export * from './ChevronsRight';
export * from './ClipBoardPlus';
export * from './Clock';
export * from './Comment';
export * from './CommentQuestion';
export * from './Comments';
export * from './CompareGrid';
export * from './Copy';
export * from './Cross';
export * from './CrossCircle';
export * from './Csv';
export * from './Download';
export * from './DownloadCloud';
export * from './DragAndDrop';
export * from './Edit';
export * from './Elements';
export * from './Envelope';
export * from './Event';
export * from './ExternalLink';
export * from './Eye';
export * from './EyeSlash';
export * from './Facebook';
export * from './File';
export * from './FileInvoice';
export * from './FilterIcon';
export * from './FitScreen';
export * from './Flag';
export * from './FlagIcon';
export * from './Gear';
export * from './Google';
export * from './GridAdd';
export * from './Hashtag';
export * from './Heart';
export * from './HeartFilled';
export * from './HorizontalSixDots';
export * from './Image';
export * from './IndicatorArrow';
export * from './Info';
export * from './Instagram';
export * from './Invoice';
export * from './Jpg';
export * from './LegalPadPlus';
export * from './Lifebuoy';
export * from './ListUnordered';
export * from './LocationPin';
export * from './Lock';
export * from './LockOpen';
export * from './LogOut';
export * from './LogoSymbol';
export * from './Mail';
export * from './MaxViewFilled';
export * from './Maximize';
export * from './Menu';
export * from './Message';
export * from './Metric';
export * from './MinViewFilled';
export * from './Minimize';
export * from './Minus';
export * from './Modules';
export * from './Monitor';
export * from './Moon';
export * from './MoreHorizontalSharp';
export * from './MoreVert';
export * from './Move';
export * from './NavMessage';
export * from './Note';
export * from './Notes';
export * from './OpenInNewTab';
export * from './Pause';
export * from './Pdf';
export * from './PencilEdit';
export * from './Phone';
export * from './Pin';
export * from './Play';
export * from './Plus';
export * from './PlusCircle';
export * from './Png';
export * from './Power';
export * from './Printer';
export * from './ProductLoading';
export * from './QuestionCircle';
export * from './Refresh';
export * from './Return';
export * from './ReturnSquare';
export * from './SavingTag';
export * from './SavingTagOutlined';
export * from './Scheme';
export * from './Scissor';
export * from './Search';
export * from './Share';
export * from './ShipmentBox';
export * from './Sliders';
export * from './Sourcing';
export * from './StackedTree';
export * from './Star';
export * from './StatusError';
export * from './StatusSuccess';
export * from './Stop';
export * from './Sun';
export * from './Target';
export * from './TargetIcon';
export * from './TaskEdit';
export * from './ThumbsUp';
export * from './ThumbsUpFilled';
export * from './Timer';
export * from './Trash';
export * from './Tree';
export * from './TrendUp';
export * from './TrendingDown';
export * from './Trip';
export * from './Twitter';
export * from './Undo';
export * from './User';
export * from './UserCheck';
export * from './UserCircle';
export * from './Users';
export * from './View';
export * from './Visit';
export * from './VisitAdd';
export * from './VisitCancelled';
export * from './VisitCompleted';
export * from './VisitRequested';
export * from './VisitScheduled';
export * from './Warning';
export * from './Xls';
export * from './primitives/ActiveAwareSvgIcon';
export * from './trendingColors';

/** Names aligned with former @mui/icons-material usage */
export { Search as SearchIcon } from './Search';
export { Trash as DeleteOutlineIcon } from './Trash';
export { Cross as CloseIcon } from './Cross';
export { Menu as MenuIcon } from './Menu';
export { ChevronDown as KeyboardArrowDownIcon } from './ChevronDown';
export { MoreHorizontalSharp as MoreHorizIcon } from './MoreHorizontalSharp';
export { CheckCircle as CheckCircleIcon } from './CheckCircle';
export { Moon as DarkModeIcon } from './Moon';
export { Sun as LightModeIcon } from './Sun';
export { LogOut as LogoutIcon } from './LogOut';
export { ListUnordered as ViewListIcon } from './ListUnordered';
export { Eye as VisibilityIcon } from './Eye';
export { EyeSlash as VisibilityOffIcon } from './EyeSlash';
